export type User = {
  id: number;
  name: string;
  role: string;
  city?: string;
  status: string;
  website: string;
  rating: number;
  phone: string;
  email: string;
};

export const users = [
  {
    id: 1,
    name: "Taller Mecánico Juan Pedro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerdepedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "liammarega@gmail.com",
  },
  {
    id: 2,
    name: "Mecánica López",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicalopez.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "lopezmecanica@gmail.com",
  },
  {
    id: 3,
    name: "Taller Rápido y Eficiente",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.0,
    phone: "+5434312345680",
    email: "tallerefectivo@gmail.com",
  },
  {
    id: 4,
    name: "Mecánica Automotriz del Río",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.8,
    phone: "+5434312345681",
    email: "delriomecanica@gmail.com",
  },
  {
    id: 5,
    name: "Taller Veloz",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.taller.veloz.com",
    rating: 4.3,
    phone: "+5434312345682",
    email: "tallerveloz@gmail.com",
  },
  {
    id: 6,
    name: "Taller Mecanico Juan Pedro",
    role: "Taller",
    status: "Contacted",
    website: "www.tallerdejuanpedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "juanpedro@example.com",
  },
  {
    id: 7,
    name: "Café Aromático",
    role: "Restaurante",
    status: "Contacted",
    website: "www.cafearomatico.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "info@cafearomatico.com",
  },
  {
    id: 6,
    name: "Mecánica Integral",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicaintegral.com",
    rating: 4.1,
    phone: "+5434312345683",
    email: "mecanicaintegral@gmail.com",
  },
  {
    id: 7,
    name: "Taller Velocidad y Precisión",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallervyp.com",
    rating: 4.6,
    phone: "+5434312345684",
    email: "tallervyp@gmail.com",
  },
  {
    id: 8,
    name: "Mecánica del Futuro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicafuturo.com",
    rating: 4.9,
    phone: "+5434312345685",
    email: "mecanicafuturo@gmail.com",
  },
  {
    id: 9,
    name: "Taller Ruedas y Motores",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.ruedasymotores.com",
    rating: 4.4,
    phone: "+5434312345686",
    email: "ruedasymotores@gmail.com",
  },
  {
    id: 10,
    name: "Mecánica Pro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Paused",
    website: "www.mecanicapro.com",
    rating: 4.7,
    phone: "+5434312345687",
    email: "mecanicapro@gmail.com",
  },
  {
    id: 11,
    name: "Taller Eficiente",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerefectivo2.com",
    rating: 4.2,
    phone: "+5434312345688",
    email: "tallerefectivo2@gmail.com",
  },
  {
    id: 12,
    name: "Mecánica Veloz y Precisa",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.velozyprecisa.com",
    rating: 4.5,
    phone: "+5434312345689",
    email: "velozyprecisa@gmail.com",
  },
  {
    id: 13,
    name: "Taller Automotriz del Parque",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.automotrizdelparque.com",
    rating: 4.0,
    phone: "+5434312345690",
    email: "delparquemecanica@gmail.com",
  },
  {
    id: 14,
    name: "Mecánica Rápida",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicarapida.com",
    rating: 4.8,
    phone: "+5434312345691",
    email: "mecanicarapida@gmail.com",
  },
  {
    id: 15,
    name: "Taller Motor y Ruedas",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.3,
    phone: "+5434312345692",
    email: "motoryruedas@gmail.com",
  },
  {
    id: 16,
    name: "Mecánica Avanzada",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Paused",
    website: "www.mecanicaavanzada.com",
    rating: 4.6,
    phone: "+5434312345693",
    email: "avanzadamotors@gmail.com",
  },
  {
    id: 17,
    name: "Taller de Confianza",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerconfianza.com",
    rating: 4.9,
    phone: "+5434312345694",
    email: "tallerconfianza@gmail.com",
  },
  {
    id: 18,
    name: "Mecánica Innovadora",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.4,
    phone: "+5434312345695",
    email: "innovativemotors@gmail.com",
  },
  {
    id: 19,
    name: "Taller Turbo",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.7,
    phone: "+5434312345696",
    email: "tallerturbo@gmail.com",
  },
  {
    id: 20,
    name: "Mecánica Velocidad Extrema",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.velocidadextrema.com",
    rating: 4.2,
    phone: "+5434312345697",
    email: "velocidadextrema@gmail.com",
  },
  {
    id: 21,
    name: "Taller Mecánico Juan Pedro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerdepedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "liammarega@gmail.com",
  },
  {
    id: 22,
    name: "Mecánica López",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicalopez.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "lopezmecanica@gmail.com",
  },
  {
    id: 23,
    name: "Taller Rápido y Eficiente",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.0,
    phone: "+5434312345680",
    email: "tallerefectivo@gmail.com",
  },
  {
    id: 24,
    name: "Mecánica Automotriz del Río",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.8,
    phone: "+5434312345681",
    email: "delriomecanica@gmail.com",
  },
  {
    id: 25,
    name: "Taller Veloz",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.taller.veloz.com",
    rating: 4.3,
    phone: "+5434312345682",
    email: "tallerveloz@gmail.com",
  },
  {
    id: 26,
    name: "Taller Mecanico Juan Pedro",
    role: "Taller",
    status: "Contacted",
    website: "www.tallerdejuanpedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "juanpedro@example.com",
  },
  {
    id: 27,
    name: "Café Aromático",
    role: "Restaurante",
    status: "Contacted",
    website: "www.cafearomatico.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "info@cafearomatico.com",
  },
  {
    id: 26,
    name: "Mecánica Integral",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicaintegral.com",
    rating: 4.1,
    phone: "+5434312345683",
    email: "mecanicaintegral@gmail.com",
  },
  {
    id: 27,
    name: "Taller Velocidad y Precisión",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallervyp.com",
    rating: 4.6,
    phone: "+5434312345684",
    email: "tallervyp@gmail.com",
  },
  {
    id: 28,
    name: "Mecánica del Futuro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicafuturo.com",
    rating: 4.9,
    phone: "+5434312345685",
    email: "mecanicafuturo@gmail.com",
  },
  {
    id: 29,
    name: "Taller Ruedas y Motores",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.ruedasymotores.com",
    rating: 4.4,
    phone: "+5434312345686",
    email: "ruedasymotores@gmail.com",
  },
  {
    id: 30,
    name: "Taller Mecánico Juan Pedro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerdepedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "liammarega@gmail.com",
  },
  {
    id: 31,
    name: "Taller Mecánico Juan Pedro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallerdepedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "liammarega@gmail.com",
  },
  {
    id: 32,
    name: "Mecánica López",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicalopez.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "lopezmecanica@gmail.com",
  },
  {
    id: 33,
    name: "Taller Rápido y Eficiente",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.0,
    phone: "+5434312345680",
    email: "tallerefectivo@gmail.com",
  },
  {
    id: 34,
    name: "Mecánica Automotriz del Río",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Not contacted",
    website: "",
    rating: 4.8,
    phone: "+5434312345681",
    email: "delriomecanica@gmail.com",
  },
  {
    id: 35,
    name: "Taller Veloz",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.taller.veloz.com",
    rating: 4.3,
    phone: "+5434312345682",
    email: "tallerveloz@gmail.com",
  },
  {
    id: 36,
    name: "Taller Mecanico Juan Pedro",
    role: "Taller",
    status: "Contacted",
    website: "www.tallerdejuanpedro.com",
    rating: 4.2,
    phone: "+5434312345678",
    email: "juanpedro@example.com",
  },
  {
    id: 37,
    name: "Café Aromático",
    role: "Restaurante",
    status: "Contacted",
    website: "www.cafearomatico.com",
    rating: 4.5,
    phone: "+5434312345679",
    email: "info@cafearomatico.com",
  },
  {
    id: 36,
    name: "Mecánica Integral",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicaintegral.com",
    rating: 4.1,
    phone: "+5434312345683",
    email: "mecanicaintegral@gmail.com",
  },
  {
    id: 37,
    name: "Taller Velocidad y Precisión",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.tallervyp.com",
    rating: 4.6,
    phone: "+5434312345684",
    email: "tallervyp@gmail.com",
  },
  {
    id: 38,
    name: "Mecánica del Futuro",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.mecanicafuturo.com",
    rating: 4.9,
    phone: "+5434312345685",
    email: "mecanicafuturo@gmail.com",
  },
  {
    id: 39,
    name: "Taller Ruedas y Motores",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.ruedasymotores.com",
    rating: 4.4,
    phone: "+5434312345686",
    email: "ruedasymotores@gmail.com",
  },
  {
    id: 40,
    name: "Taller Ruedas y Motores",
    role: "Taller",
    city: "Paraná, Entre Ríos",
    status: "Contacted",
    website: "www.ruedasymotores.com",
    rating: 4.4,
    phone: "+5434312345686",
    email: "ruedasymotores@gmail.com",
  },
];

export const columns = [
  {
    id: "name",
    label: "NAME",
  },
  {
    id: "role",
    label: "ROLE",
  },
  {
    id: "website",
    label: "WEBSITE",
  },
  {
    id: "phone",
    label: "PHONE",
  },
  {
    id: "email",
    label: "EMAIL",
  },
  {
    id: "rating",
    label: "RAITING",
  },
  {
    id: "sendMessage",
    label: "SEND MESSAGE",
  },
  {
    id: "status",
    label: "STATUS",
  },
];
